ARG SOURCE_CODE=.

FROM registry.access.redhat.com/ubi9/go-toolset:1.26.2-1777889793@sha256:1c1259373e6feb4b57de490452379c40888cf6e876154cd2ace17eae9c64a7ea as builder

# Build args to be used at this step
ARG SOURCE_CODE
WORKDIR /workspace

USER root
RUN dnf install -y mailcap

COPY ${SOURCE_CODE}/go.mod .
COPY ${SOURCE_CODE}/go.sum .
COPY ${SOURCE_CODE}/ ./

# Set the /workspace directory as safe for Git
RUN git config --global --add safe.directory /workspace

RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build CGO_ENABLED=0 GOFIPS140=v1.0.0 go build -tags no_openssl -v -o dist/argoexec ./cmd/argoexec

####################################################################################################
FROM registry.redhat.io/ubi9/ubi-minimal:9.5 AS argoexec


ARG CI_CONTAINER_VERSION

WORKDIR /bin

COPY --from=builder /workspace/dist/argoexec /bin/
COPY --from=builder /etc/mime.types /etc/mime.types
COPY --from=builder /workspace/hack/ssh_known_hosts /etc/ssh/
COPY --from=builder /workspace/hack/nsswitch.conf /etc/

RUN chmod +x /bin/argoexec && ln -s /bin/argoexec /bin/argoexec-fips

USER 2000

ENTRYPOINT [ "/bin/argoexec" ]
