name: "Create and tag a build"
description: "This workflow will build and tag the image with the provided tag."
inputs:
  TAG:
    description: "tag image with provided tag"
    required: true
  TAG_LATEST:
    description: "tag image with latest and main tags"
    required: false
  DOCKERFILE:
    description: "path to dockerfile"
    required: true
runs:
  using: "composite"
  steps:
    - name: Build Image
      uses: opendatahub-io/data-science-pipelines-operator/.github/actions/build@main
      env:
        IMG: quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_REPO }}:${{ inputs.TAG }}
        TARGET_IMAGE_TAG: ${{ inputs.TAG }}
      with:
        OVERWRITE: true
        IMAGE_REPO: ${{ env.IMAGE_REPO }}
        DOCKERFILE: ${{ inputs.DOCKERFILE }}
        GH_REPO: ${{ github.repository }}
    - name: Tag latest
      shell: bash
      if: inputs.TAG_LATEST == 'true'
      env:
        IMG: quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_REPO }}
        NEWEST_TAG: ${{ inputs.TAG }}
      run: |
        podman tag ${IMG}:${NEWEST_TAG} ${IMG}:latest
        podman push ${IMG}:latest
        podman tag ${IMG}:${NEWEST_TAG} ${IMG}:main
        podman push ${IMG}:main
